<?php

namespace Database\Factories;

use App\Models\Trip;
use App\Models\TripSeat;
use Illuminate\Database\Eloquent\Factories\Factory;

/**
 * @extends Factory<TripSeat>
 */
class TripSeatFactory extends Factory
{
    /**
     * Define the model's default state.
     *
     * Seats are normally generated by TripObserver; this factory exists for the
     * rare test that needs a stray seat, so seat_no must not clash with those.
     *
     * @return array<string, mixed>
     */
    public function definition(): array
    {
        return [
            'trip_id' => Trip::factory(),
            'seat_no' => $this->faker->unique()->numberBetween(1000, 9999),
        ];
    }
}
